server:
  port: 9123
spring:
  shardingsphere:
    datasource:
      names: "order0,order1"
      order0:
        driver-class-name: "org.mariadb.jdbc.Driver"
        username: "root"
        password: "root"
        type: "com.alibaba.druid.pool.DruidDataSource"
        url: "jdbc:mariadb://192.168.3.132:3306/order_00?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8"
      order1:
        driver-class-name: "org.mariadb.jdbc.Driver"
        username: "root"
        password: "root"
        type: "com.alibaba.druid.pool.DruidDataSource"
        url: "jdbc:mariadb://192.168.3.133:3306/order_01?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8"
    sharding:
      #defaultDataSourceName: order0
      #broadcast-tables: t_config
      default-database-strategy:
        inline:
          sharding-column: "user_id"
          algorithm-expression: "order$->{(int) (user_id / 4) % 2}"
      binding-tables: "order_master"
      tables:
        order_master:
          actual-data-nodes: "order$->{0..1}.order_master_000$->{0..3}"
          table-strategy:
            inline:
              sharding-column: "user_id"
              algorithm-expression: "order_master_000$->{user_id % 4}"
#          key-generator:
#            column: order_id
#            type: SNOWFLAKE
    props:
      sql:
        show: true

mybatis:
  mapper-locations: "classpath:mapper/*.xml"