server:
  port: 6060
  servlet:
    session:
      timeout: 60

spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3306/trade?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8"
    username: "root"
    password: "root"
    driver-class-name: "org.mariadb.jdbc.Driver"
    type: "com.alibaba.druid.pool.DruidDataSource"
  application:
    name: logger-center-service
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 50000
    jedis:
      pool:
        max-idle: 50
        min-idle: 20

logging:
  config: "classpath:logback.xml"

mybatis:
  mapper-locations: "classpath:mapper/*.xml"


jwt:
  secret: "wwaFDVveDsasx21dc=634%3&%$$2r"