-- user model --
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `nick` VARCHAR(16) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `gender` TINYINT NOT NULL DEFAULT 0,
    `telephone` BIGINT,
    `password` VARCHAR(64) NOT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    UNIQUE KEY `uni_idx_nick`(`nick`),
    UNIQUE KEY `uni_idx_email`(`email`),
    UNIQUE KEY `uni_idx_telephone`(`telephone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `seller` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(80) NOT NULL DEFAULT ' ',
    `remark_score` DECIMAL(2,1) NOT NULL DEFAULT 0,
    `disabled_flag` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

