server:
  port: 8000
spring:
  shardingsphere:
    datasource:
      names: "product-db-0, product-db-1, sequence"
      product-db-0:
        driver-class-name: "org.mariadb.jdbc.Driver"
        username: "root"
        password: "root"
        type: "com.alibaba.druid.pool.DruidDataSource"
        url: "jdbc:mariadb://127.0.0.1:3306/product_db_0?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8"
      product-db-1:
        driver-class-name: "org.mariadb.jdbc.Driver"
        username: "root"
        password: "root"
        type: "com.alibaba.druid.pool.DruidDataSource"
        url: "jdbc:mariadb://127.0.0.1:3306/product_db_1?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8"
      sequence:
        driver-class-name: "org.mariadb.jdbc.Driver"
        username: "root"
        password: "root"
        type: "com.alibaba.druid.pool.DruidDataSource"
        url: "jdbc:mariadb://127.0.0.1:3306/sequence_db?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8"
    props:
      sql:
        show: true